version: "3.8"

services:
  bluebook:
    #image: mannx/bluebook:beta
    image: bluebook:latest
    container_name: bluebook
    ports:
      - 8080:8080
    environment:
      - TZ=Canada/Atlantic      
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data:z
      - ./import_data:/import
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: on-failure
