version: "3.8"

services:
  bluebook:
          image: mannx/bluebook:beta
    container_name: bluebook
    ports:
      - 8080:8080
    environment:
      - TZ=Canada/Atlantic      
    volumes:
      - ./data:/data
      - ./import_data:/import
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: on-failure
