#name: Docker Image CI
name: bb-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
        
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          #push: true
          #tags: mannx/bluebook:latest
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
